#!/usr/bin/env bash
# WS-V2-006 G5: Bootstrap Environment
# Three modes: audit (read-only check), dev (scoped env for AI), runtime (full env).
# Runtime requires --unlock-runtime. Never prints values. Never copies full .env.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"

WORKTREE=""
SOURCE_ENV="${GUIYI_ENV_SOURCE:-$REPO_ROOT/.env}"
MODE="audit"
APPLY=false
CONFIRM_PRODUCTION=false
UNLOCK_RUNTIME=false
QUIET=false

usage() {
  cat <<'EOF'
Usage: scripts/env/bootstrap_worktree_env.sh --worktree <path> [options]

Modes:
  --audit                (default) Read-only environment check — never writes
  --dev                  Scoped .env for AI development — whitelisted keys only
  --runtime              Full runtime environment — requires --unlock-runtime

Options:
  --source <path>        Existing env file to filter (default: GUIYI_ENV_SOURCE)
  --apply                Perform the change; default is dry-run
  --confirm-production   Allow running when APP_ENV=production is already set
  --unlock-runtime       Required for runtime mode (explicit human unlock)
  --quiet                Print less
  -h, --help             Show help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --worktree) WORKTREE="${2:-}"; shift 2 ;;
    --source) SOURCE_ENV="${2:-}"; shift 2 ;;
    --audit) MODE="audit"; shift ;;
    --dev) MODE="dev"; shift ;;
    --runtime) MODE="runtime"; shift ;;
    --apply) APPLY=true; shift ;;
    --dry-run) APPLY=false; shift ;;
    --confirm-production) CONFIRM_PRODUCTION=true; shift ;;
    --unlock-runtime) UNLOCK_RUNTIME=true; shift ;;
    --quiet) QUIET=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# Runtime gate: require explicit human unlock
if [[ "$MODE" == "runtime" && "$UNLOCK_RUNTIME" != true ]]; then
  echo "Runtime mode requires explicit --unlock-runtime (human confirmation)" >&2
  exit 1
fi

# Production guard
if [[ "${APP_ENV:-}" == "production" && "$CONFIRM_PRODUCTION" != true ]]; then
  echo "Production env requires explicit --confirm-production" >&2
  exit 1
fi

# Resolve worktree
if [[ -z "$WORKTREE" ]]; then
  WORKTREE="$REPO_ROOT"
fi
WORKTREE="$(cd "$WORKTREE" 2>/dev/null && pwd -P || true)"
[[ -n "$WORKTREE" && -d "$WORKTREE" ]] || { echo "Worktree missing: ${WORKTREE:-<empty>}" >&2; exit 4; }

# Resolve source env
SOURCE_ENV_EXPANDED="${SOURCE_ENV/#\~/$HOME}"
if [[ "$SOURCE_ENV_EXPANDED" != /* ]]; then
  SOURCE_ENV_EXPANDED="$(cd "$(dirname "$SOURCE_ENV_EXPANDED")" 2>/dev/null && pwd -P)/$(basename "$SOURCE_ENV_EXPANDED")"
fi
[[ -f "$SOURCE_ENV_EXPANDED" ]] || { echo "Env source missing: $SOURCE_ENV" >&2; exit 4; }

TARGET="$WORKTREE/.env"

# ── Key whitelists per mode ───────────────────────────────────────────

# Audit: no keys needed (read-only check)
# Dev: minimal set needed for AI development
# Runtime: all keys (whitelisted for safety)

# Dev mode allowed keys — never hardcode full runtime secrets
DEV_ALLOWED_KEYS="^(# )?(PYTHONPATH|GUIYI_WORKTREE_ROOT|GUIYI_ENV|GUIYI_LOG_LEVEL|LOG_LEVEL|DEBUG|PYTHONUNBUFFERED|LANG|LC_ALL|TZ|APP_ENV|GUIYI_AI_|PATH|HOME|USER|SHELL)="

# Runtime mode allowed keys — broader but still filtered
RUNTIME_ALLOWED_KEYS="^(# )?(DATABASE_URL|REDIS_URL|RQDATA_|GUIYI_|PYTHONPATH|LOG_LEVEL|DEBUG|APP_ENV|LANG|LC_ALL|TZ|PATH|HOME|USER|SHELL|GUIYI_WORKTREE_ROOT|GUIYI_AI_)="

# ── Filter function ───────────────────────────────────────────────────

filter_env() {
  local source="$1" mode="$2"
  local allowed_pattern

  case "$mode" in
    audit) allowed_pattern="$DEV_ALLOWED_KEYS" ;;
    dev) allowed_pattern="$DEV_ALLOWED_KEYS" ;;
    runtime) allowed_pattern="$RUNTIME_ALLOWED_KEYS" ;;
    *) echo "Unknown mode: $mode" >&2; return 1 ;;
  esac

  # Write header
  echo "# WORKTREE ENV — generated by bootstrap_worktree_env.sh"
  echo "# mode=$mode worktree=$WORKTREE"
  echo "# generated_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""

  # Filter source .env through key whitelist — never print values during filtering
  grep -qE "$allowed_pattern" "$source" 2>/dev/null || true
  grep -E "$allowed_pattern" "$source" 2>/dev/null || true

  echo ""
  echo "# End of scoped env"
}

# ── Audit mode ────────────────────────────────────────────────────────

do_audit() {
  if [[ "$QUIET" != true ]]; then
    echo "[AUDIT] Mode: audit (read-only)"
    echo "  source: $SOURCE_ENV_EXPANDED"
    echo "  worktree: $WORKTREE"
    echo "  keys_found: $(grep -cE "$DEV_ALLOWED_KEYS" "$SOURCE_ENV_EXPANDED" 2>/dev/null || echo 0)"
  fi
  # Audit never writes, always exit 0
  return 0
}

# ── Apply (dev/runtime) ───────────────────────────────────────────────

do_apply() {
  local mode="$1"

  # Check target existence
  if [[ -e "$TARGET" || -L "$TARGET" ]]; then
    echo "Target .env already exists; refusing to overwrite: $TARGET" >&2
    exit 1
  fi

  if [[ "$APPLY" != true ]]; then
    if [[ "$QUIET" != true ]]; then
      echo "[DRY-RUN] Mode: $mode"
      echo "  worktree: $WORKTREE"
      echo "  source:   $SOURCE_ENV_EXPANDED"
      echo "  target:   $TARGET"
    fi
    return 0
  fi

  # Generate scoped .env — never symlink to full source
  filter_env "$SOURCE_ENV_EXPANDED" "$mode" > "$TARGET"
  chmod 600 "$TARGET" 2>/dev/null || true

  if [[ "$QUIET" != true ]]; then
    echo "[OK] Mode: $mode — scoped .env written"
    echo "  worktree: $WORKTREE"
    echo "  target:   $TARGET"
    local key_count
    key_count="$(grep -cE '^[A-Z]' "$TARGET" 2>/dev/null || echo 0)"
    echo "  key_count: $key_count"
  fi
}

# ── Main dispatch ─────────────────────────────────────────────────────

case "$MODE" in
  audit) do_audit ;;
  dev) do_apply "dev" ;;
  runtime) do_apply "runtime" ;;
  *) echo "Unknown mode: $MODE" >&2; exit 2 ;;
esac
