<script setup lang="ts">
import type { MarketHomeLocalFilter } from '@/utils/marketHomeWorkspace'
defineProps<{ summary: { price_up_count: number; price_down_count: number; price_flat_count: number; daily_up_count: number; daily_down_count: number; daily_neutral_count: number; daily_unavailable_count: number; aligned_up_count: number; aligned_down_count: number } | null; active: MarketHomeLocalFilter; eventCount: number; latestEventTime: string | null }>()
defineEmits<{ filter: [kind: MarketHomeLocalFilter] }>()
</script>

<template><section v-if="summary" class="summary" aria-label="本地概览筛选"><div><span>涨/跌/平</span><button :class="{active:active==='up'}" @click="$emit('filter','up')">上涨 {{summary.price_up_count}}</button><button :class="{active:active==='down'}" @click="$emit('filter','down')">下跌 {{summary.price_down_count}}</button><button :class="{active:active==='flat'}" @click="$emit('filter','flat')">平 {{summary.price_flat_count}}</button></div><div><span>日线</span><button :class="{active:active==='daily-up'}" @click="$emit('filter','daily-up')">上 {{summary.daily_up_count}}</button><button :class="{active:active==='daily-down'}" @click="$emit('filter','daily-down')">下 {{summary.daily_down_count}}</button><button :class="{active:active==='daily-neutral'}" @click="$emit('filter','daily-neutral')">中 {{summary.daily_neutral_count}}</button><button :class="{active:active==='daily-unavailable'}" @click="$emit('filter','daily-unavailable')">不足 {{summary.daily_unavailable_count}}</button></div><div><span>同向</span><button :class="{active:active==='aligned'}" @click="$emit('filter','aligned')">多/空 {{summary.aligned_up_count}}/{{summary.aligned_down_count}}</button></div><div><span>HTDY Event</span><button :class="{active:active==='with-event'}" @click="$emit('filter','with-event')">{{eventCount}}<small>最新 {{latestEventTime??'—'}}</small></button></div><button v-if="active!=='all'" class="summary__clear" @click="$emit('filter','all')">清除筛选</button></section></template>

<style scoped>.summary{display:flex;gap:8px;flex-wrap:wrap;align-items:stretch}.summary>div{display:flex;align-items:center;gap:4px;border:.5px solid var(--gy-border);border-radius:var(--gy-radius-md);background:var(--gy-bg-panel);padding:6px 8px}.summary span{color:var(--gy-text-muted);font-size:var(--gy-font-size-xs)}.summary button{border:0;border-radius:var(--gy-radius-sm);background:transparent;padding:4px 6px;cursor:pointer}.summary button.active{background:var(--gy-accent-soft);color:var(--gy-accent)}.summary small{display:block;color:var(--gy-text-muted);font-weight:400;margin-top:3px}.summary__clear{border:.5px solid var(--gy-border)!important;background:var(--gy-bg-panel)!important;padding:8px 10px!important}</style>
