<script setup lang="ts">
import MarketStateIcon from './MarketStateIcon.vue'
import type { MarketHomeIconState } from '@/utils/marketHomeIcons'
import type { MarketHomeRow } from '@/utils/marketHomeViewModel'
defineProps<{ rows: MarketHomeRow[] }>()
defineEmits<{ open: [row: MarketHomeRow] }>()
const state = (value: string): MarketHomeIconState => value === 'up' || value === 'down' || value === 'neutral' || value === 'unavailable' ? value : 'unavailable'
const alignmentState = (value: string): MarketHomeIconState | null => value.startsWith('aligned') ? 'aligned' : value === 'neutral' ? 'neutral' : value === 'unavailable' ? 'unavailable' : null
const alignmentDirection = (value: string): MarketHomeIconState | null => value === 'aligned-up' ? 'up' : value === 'aligned-down' ? 'down' : null
const eventState = (row: MarketHomeRow): MarketHomeIconState | null => !row.event ? null : row.event.result_codes.length === 2 ? 'aligned' : row.event.result_codes[0] === 'buy' ? 'up' : 'down'
const eventLabel = (row: MarketHomeRow) => !row.event ? '—' : row.event.result_codes.length === 2 ? '双向观察' : row.event.result_codes[0] === 'buy' ? '买观察' : '卖观察'
const percentage = (value: number | null) => value === null ? '—' : `${(value * 100).toFixed(2)}%`
</script>
<template><div class="table-wrap"><table><caption>最近完整交易日收盘快照</caption><thead><tr><th scope="col">品种</th><th scope="col">板块</th><th scope="col">收盘</th><th scope="col">1D</th><th scope="col">5D</th><th scope="col">量比</th><th scope="col">OI</th><th scope="col">日</th><th scope="col">周</th><th scope="col">同向</th><th scope="col">HTDY</th><th scope="col">数据</th></tr></thead><tbody><tr v-for="row in rows" :key="row.symbol" tabindex="0" @click="$emit('open',row)" @keyup.enter="$emit('open',row)"><th scope="row">{{row.symbol.toUpperCase()}} {{row.product_name}}</th><td>{{row.sector}}</td><td>{{row.close}}</td><td>{{percentage(row.price_change_1d)}}</td><td>{{percentage(row.price_change_5d)}}</td><td>{{row.volume_ratio20??'—'}}</td><td>{{row.oi_change_1d??'—'}}</td><td><MarketStateIcon :state="state(row.dailyState)"/></td><td><MarketStateIcon :state="state(row.weeklyState)"/></td><td><span v-if="alignmentState(row.alignment)" class="alignment"><MarketStateIcon :state="alignmentState(row.alignment)!"/><MarketStateIcon v-if="alignmentDirection(row.alignment)" :state="alignmentDirection(row.alignment)!" size="micro"/></span><span v-else>未同向</span></td><td><span v-if="eventState(row)" class="event"><MarketStateIcon :state="eventState(row)!" size="micro"/>{{eventLabel(row)}}</span><span v-else>—</span></td><td>{{row.data_as_of}}</td></tr></tbody></table></div></template>
<style scoped>.table-wrap{overflow-x:auto;border:.5px solid var(--gy-border);border-radius:var(--gy-radius-lg)}table{width:100%;border-collapse:collapse;min-width:1050px;font-size:var(--gy-font-size-sm)}caption{text-align:left;padding:10px 12px;color:var(--gy-text-muted)}th,td{padding:9px 10px;border-top:.5px solid var(--gy-border);text-align:left;white-space:nowrap}thead th{position:sticky;top:0;background:var(--gy-table-header)}tbody tr{cursor:pointer}tbody tr:hover{background:var(--gy-bg-hover)}tbody tr:focus-visible{outline:2px solid var(--gy-accent);outline-offset:-2px}.event,.alignment{display:flex;align-items:center;gap:5px}@media(max-width:1439px){th:nth-child(5),td:nth-child(5),th:nth-child(6),td:nth-child(6){display:none}}@media(min-width:768px) and (max-width:1199px){tbody th:first-child,thead th:first-child{position:sticky;left:0;background:var(--gy-bg-panel);z-index:1}thead th:first-child{background:var(--gy-table-header);z-index:2}}@media(max-width:767px){table{display:none}}</style>
