import type { GlobalThemeOverrides } from 'naive-ui'

/**
 * Naive UI 亮色主题覆盖。
 * Naive 在 JS 中推导 alpha 变体，因此此处须使用具体色值；与 tokens.css 保持一致。
 */
// Naive UI derives alpha variants in JavaScript and therefore requires concrete
// color values here. Keep these values aligned with tokens.css.
const palette = {
  app: '#F8FAFC',
  canvas: '#FFFFFF',
  panel: '#FFFFFF',
  panelStrong: '#F8FAFC',
  elevated: '#F2F4F7',
  overlay: '#FFFFFF',
  hover: 'rgba(16, 24, 40, 0.04)',
  selected: 'rgba(37, 99, 235, 0.1)',
  border: '#E4E7EC',
  primaryText: '#101828',
  secondaryText: '#475467',
  mutedText: '#667085',
  disabledText: '#98A2B3',
  accent: '#2563EB',
  accentHover: '#1D4ED8',
  accentPressed: '#1E40AF',
  onAccent: '#FFFFFF',
  controlActive: '#2563EB',
  controlActiveHover: '#1D4ED8',
  controlPressed: '#1E40AF',
  controlDisabled: '#F2F4F7',
} as const

/** 导出给 NConfigProvider 的全局 theme-overrides */
export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: palette.accent,
    primaryColorHover: palette.accentHover,
    primaryColorPressed: palette.accentPressed,
    primaryColorSuppl: palette.accentHover,
    bodyColor: palette.app,
    cardColor: palette.panel,
    modalColor: palette.panel,
    popoverColor: palette.overlay,
    tableColor: palette.panel,
    inputColor: palette.panelStrong,
    actionColor: palette.panelStrong,
    borderColor: palette.border,
    dividerColor: palette.border,
    textColor1: palette.primaryText,
    textColor2: palette.secondaryText,
    textColor3: palette.mutedText,
    placeholderColor: palette.mutedText,
    fontFamily: "'PingFang SC', 'Microsoft YaHei', system-ui, -apple-system, sans-serif",
    fontFamilyMono: "'SFMono-Regular', 'SF Mono', 'Roboto Mono', Menlo, monospace",
    borderRadius: '8px',
    heightMedium: '34px',
    heightSmall: '30px',
  },
  Layout: {
    color: palette.app,
    siderColor: palette.canvas,
    headerColor: palette.canvas,
  },
  Menu: {
    color: 'transparent',
    groupTextColor: palette.mutedText,
    itemColorHover: palette.hover,
    itemColorActive: palette.selected,
    itemColorActiveHover: palette.selected,
    itemTextColor: palette.secondaryText,
    itemTextColorHover: palette.primaryText,
    itemTextColorActive: palette.accentHover,
    itemTextColorActiveHover: palette.accentHover,
    itemIconColor: palette.mutedText,
    itemIconColorHover: palette.primaryText,
    itemIconColorActive: palette.accentHover,
    itemHeight: '38px',
    itemBorderRadius: '5px',
  },
  Card: {
    color: palette.panel,
    borderColor: palette.border,
    borderRadius: '10px',
    paddingSmall: '14px',
  },
  DataTable: {
    thColor: '#F8FAFC',
    thColorHover: '#F8FAFC',
    tdColor: palette.panel,
    tdColorHover: palette.hover,
    borderColor: palette.border,
    thTextColor: palette.mutedText,
    tdTextColor: palette.secondaryText,
  },
  Drawer: {
    color: palette.panel,
  },
  Radio: {
    buttonColor: palette.panelStrong,
    buttonColorActive: palette.controlActive,
    buttonTextColor: palette.secondaryText,
    buttonTextColorActive: palette.onAccent,
    buttonTextColorHover: palette.primaryText,
    buttonBorderColor: palette.border,
    buttonBorderColorActive: palette.accentHover,
    buttonBorderColorHover: palette.accentHover,
    textColorDisabled: palette.disabledText,
  },
  Select: {
    peers: {
      InternalSelection: {
        color: palette.panelStrong,
        colorActive: palette.elevated,
        colorDisabled: palette.controlDisabled,
        textColor: palette.primaryText,
        textColorDisabled: palette.disabledText,
        border: `1px solid ${palette.border}`,
        borderActive: `1px solid ${palette.accentHover}`,
        borderFocus: `1px solid ${palette.accentHover}`,
        borderHover: `1px solid ${palette.accentHover}`,
      },
      InternalSelectMenu: {
        color: palette.overlay,
        optionColorPending: palette.hover,
        optionColorActive: palette.controlActive,
        optionColorActivePending: palette.controlActiveHover,
        optionTextColor: palette.secondaryText,
        optionTextColorActive: palette.onAccent,
        optionTextColorDisabled: palette.disabledText,
      },
    },
  },
  Tabs: {
    tabTextColorLine: palette.mutedText,
    tabTextColorActiveLine: palette.accentHover,
    tabTextColorHoverLine: palette.primaryText,
    tabTextColorDisabledLine: palette.disabledText,
    tabTextColorSegment: palette.secondaryText,
    tabTextColorActiveSegment: palette.onAccent,
    tabTextColorHoverSegment: palette.primaryText,
    tabTextColorDisabledSegment: palette.disabledText,
    tabColorSegment: palette.panelStrong,
    tabColorSegmentActive: palette.controlActive,
    barColor: palette.accent,
  },
  Button: {
    borderRadiusSmall: '5px',
    borderRadiusMedium: '8px',
    colorPrimary: palette.controlActive,
    colorHoverPrimary: palette.controlActiveHover,
    colorPressedPrimary: palette.controlPressed,
    colorFocusPrimary: palette.controlActive,
    colorDisabledPrimary: palette.controlDisabled,
    textColorPrimary: palette.onAccent,
    textColorHoverPrimary: palette.onAccent,
    textColorPressedPrimary: palette.onAccent,
    textColorFocusPrimary: palette.onAccent,
    textColorDisabledPrimary: palette.disabledText,
    borderPrimary: `1px solid ${palette.accentHover}`,
    borderHoverPrimary: `1px solid ${palette.accentHover}`,
    borderPressedPrimary: `1px solid ${palette.accentPressed}`,
    borderFocusPrimary: `1px solid ${palette.accentHover}`,
    borderDisabledPrimary: `1px solid ${palette.border}`,
  },
}
