import { expect, test } from '@playwright/test'
import { installNewowProductFixtures, newowRoute, assertNoUnexpectedRequests, productRequests } from './newow-product.helpers.mjs'

for (const width of [1440, 390]) {
  test(`nine UI items: display controls, exact facts, formulas and dual tracks at ${width}`, async ({ page }) => {
    const fixture = await installNewowProductFixtures(page, { dualMarket: true })
    await page.setViewportSize({ width, height: 900 })
    await page.goto(newowRoute())
    const stage = page.getByTestId('newow-product-chart-stage')
    await expect(stage).toHaveAttribute('data-auxiliary-state', 'ready')
    const action = stage.locator('[data-action-id]').first()
    const id = await action.getAttribute('data-action-id')
    await action.click()
    await expect(page.getByRole('dialog')).toContainText(id)
    await page.getByRole('button', { name: '知道了', exact: true }).click()
    await stage.getByRole('button', { name: '简洁标记', exact: true }).click()
    await expect(stage.locator('[data-action-id]')).toHaveCount(0)
    await stage.getByRole('button', { name: '详细标记', exact: true }).click()
    await stage.getByText('图层', { exact: true }).click()
    await stage.getByRole('button', { name: '建仓 / 清仓', exact: true }).click()
    await expect(stage.locator('[data-action-id]')).toHaveCount(0)
    await stage.getByRole('button', { name: '建仓 / 清仓', exact: true }).click()
    await stage.getByText('图层', { exact: true }).click()
    await stage.getByRole('button', { name: '双策略对照', exact: true }).click()
    await expect(stage).toHaveAttribute('data-comparison-active', 'true')
    expect(productRequests(fixture, 'chart').filter(item => item.strategy === 'oscillation')).toHaveLength(1)
    const osc = stage.locator('[data-origin-strategy="oscillation"]').first()
    await osc.click()
    await expect(page.getByRole('dialog')).toContainText('RB · 震荡 · 1d · RB2605')
    await page.getByRole('button', { name: '知道了', exact: true }).click()
    await stage.getByRole('button', { name: '趋势上轨', exact: true }).click()
    await expect(stage.locator('[data-origin-strategy="trend"]')).toHaveCount(0)
    await expect(stage.locator('[data-origin-strategy="oscillation"]').first()).toBeVisible()
    await stage.getByRole('button', { name: '趋势上轨', exact: true }).click()
    await stage.getByRole('button', { name: '背景着色', exact: true }).click()
    await expect(stage.getByRole('button', { name: '背景着色', exact: true })).toHaveAttribute('aria-pressed', 'false')
    await stage.getByRole('button', { name: '简洁标记', exact: true }).click()
    await expect(stage.locator('[data-origin-strategy="oscillation"]').first()).toBeVisible()
    await stage.getByRole('button', { name: '详细标记', exact: true }).click()
    await stage.getByRole('button', { name: '双策略对照', exact: true }).click()
    await expect(stage).toHaveAttribute('data-comparison-active', 'false')
    await expect(stage.locator('.newow-product-chart-stage__action-callouts:not(.newow-product-chart-stage__dual-tracks) [data-action-id]').first()).toBeVisible()
    await stage.getByRole('button', { name: '双策略对照', exact: true }).click()
    await expect(stage).toHaveAttribute('data-comparison-active', 'true')
    await page.screenshot({ path: `/private/tmp/newow-ui-nine-dual-${width}.png`, fullPage: false })
    const chartBox = await stage.locator('.newow-product-chart-stage__chart').boundingBox()
    const auxiliaryBox = await stage.locator('.newow-product-chart-stage__auxiliary-toolbar').boundingBox()
    expect(auxiliaryBox.y).toBeGreaterThan(chartBox.y + chartBox.height * .65)
    await page.getByRole('button', { name: '公式速查', exact: true }).first().click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toContainText('A=MAp(T,7)')
    await dialog.getByRole('combobox', { name: '公式速查主题' }).selectOption('trend_reversal')
    await expect(dialog).toContainText('WR1>97')
    await page.screenshot({ path: `/private/tmp/newow-ui-nine-formula-${width}.png` })
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '紧凑列表', exact: true }).click()
    await expect(page.locator('.newow-reference__cards')).toHaveClass(/is-compact-list/)
    await expect(page.getByRole('button', { name: '完整窗口', exact: true })).toHaveAttribute('title', /完整/)
    await page.screenshot({ path: `/private/tmp/newow-ui-nine-reference-${width}.png` })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    assertNoUnexpectedRequests(fixture)
  })
}

test('incompatible companion fails closed while single-strategy facts remain readable', async ({ page }) => {
  const fixture = await installNewowProductFixtures(page)
  await page.goto(newowRoute())
  const stage = page.getByTestId('newow-product-chart-stage')
  await expect(stage).toHaveAttribute('data-auxiliary-state', 'ready')
  await stage.getByRole('button', { name: '双策略对照', exact: true }).click()
  await expect(page.getByText('两策略的窗口、时间或物理合约事实无法对齐，已停止叠加。')).toBeVisible()
  await expect(stage).toHaveAttribute('data-comparison-active', 'false')
  await expect(stage.locator('[data-action-id]').first()).toBeVisible()
  assertNoUnexpectedRequests(fixture)
})
