import { expect, test } from '@playwright/test'
import { installNewowProductFixtures, buildNewowFixtureEnvelopeForTest, newowRoute, productRequests, assertNoUnexpectedRequests } from './newow-product.helpers.mjs'

test('white summary, lazy reference, bounded quote and native explanation dialog remain identity-safe', async ({ page }) => {
  const fixture = await installNewowProductFixtures(page)
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto(newowRoute())
  const workspace = page.locator('[data-detail-workspace="newow"]')
  await expect(workspace).toHaveAttribute('data-chart-state', 'ready')
  await expect(workspace).toHaveAttribute('data-auxiliary-state', 'ready')
  await expect(page.locator('.newow-detail-light')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  expect(productRequests(fixture, 'explanation')).toHaveLength(0)
  expect(productRequests(fixture, 'comparator')).toHaveLength(0)
  expect(productRequests(fixture, 'reference')).toHaveLength(0)
  await expect(page.locator('.quote-header')).toContainText('最近日线收盘')
  await expect(page.locator('.quote-header__price strong')).not.toHaveText('—')
  const quoteRequests = () => fixture.requests.filter(item => item.url.pathname.endsWith('/bars/page'))
  expect(quoteRequests()).toHaveLength(1)
  expect(Object.fromEntries(quoteRequests()[0].url.searchParams)).toMatchObject({ frequency: '1d', limit: '2', symbol: 'rb', series_kind: 'actual_dominant' })
  await page.screenshot({ path: '/private/tmp/newow-task2-shell.png' })
  const info = page.getByRole('button', { name: '策略信息', exact: true })
  await info.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('当前综合解释')
  await expect(dialog).toContainText('策略当前为建仓状态')
  await expect(dialog.getByRole('status')).toContainText('部分解释证据不足')
  const rawReason = dialog.getByText('NEWOW_TARGET_SOURCE_UNPROVEN', { exact: true }).first()
  await expect(rawReason).not.toBeVisible()
  await expect(dialog.getByTestId('newow-readable-facts')).toContainText('偏多')
  await expect(dialog.getByTestId('newow-readable-facts')).not.toContainText('LONG_BIAS')
  await expect(dialog.getByRole('button', { name: '知道了', exact: true })).toHaveCSS('background-color', 'rgb(54, 90, 245)')
  await page.screenshot({ path: '/private/tmp/newow-task2-dialog.png' })
  await dialog.getByText('来源与证据详情', { exact: true }).click()
  await expect(rawReason).toBeVisible()
  await dialog.getByText('来源与证据详情', { exact: true }).click()
  expect(productRequests(fixture, 'comparator')).toHaveLength(0)
  for (let index = 0; index < 10; index++) {
    await page.keyboard.press('Tab')
    expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  }
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(info).toBeFocused()
  await page.getByRole('button', { name: '展开详情', exact: true }).click()
  await expect(page.locator('#newow-details')).toBeVisible()
  expect(productRequests(fixture, 'explanation')).toHaveLength(1)
  await page.getByRole('button', { name: '收起详情', exact: true }).click()
  await page.locator('.newow-reference').scrollIntoViewIfNeeded()
  await expect(page.getByTestId('newow-reference-summary')).toBeVisible()
  await expect(page.locator('article[data-reference-category]')).toHaveCount(2)
  await expect(page.locator('.newow-reference table')).toHaveCount(0)
  expect(productRequests(fixture, 'reference')).toHaveLength(1)
  await page.locator('.newow-summary').scrollIntoViewIfNeeded()
  await page.locator('.newow-reference').scrollIntoViewIfNeeded()
  expect(productRequests(fixture, 'reference')).toHaveLength(1)
  await page.getByRole('button', { name: '加载更多参考历史', exact: true }).click()
  await expect(page.locator('article[data-reference-category]')).toHaveCount(4)
  expect(productRequests(fixture, 'reference')).toHaveLength(2)
  await page.getByRole('button', { name: '页面比较说明', exact: true }).click()
  await expect(dialog).toContainText('独立理论结果')
  await expect(dialog.locator('[data-testid="newow-explanation-panel"]')).toHaveCount(0)
  await page.getByRole('button', { name: '知道了', exact: true }).click()
  await info.click()
  await expect(dialog).toBeVisible()
  await page.getByRole('button', { name: '60m', exact: true }).evaluate(element => element.click())
  await expect(workspace).toHaveAttribute('data-frequency', '60m')
  await expect(page.locator('#newow-details')).toHaveCount(0)
  await expect(dialog).not.toBeVisible()
  expect(quoteRequests()).toHaveLength(1)
  assertNoUnexpectedRequests(fixture)
})

test('historical action dialog uses marker facts without requesting current explanation', async ({ page }) => {
  const fixture = await installNewowProductFixtures(page)
  await page.goto(newowRoute())
  await expect(page.locator('[data-detail-workspace="newow"]')).toHaveAttribute('data-chart-state', 'ready')
  await page.locator('.newow-summary__facts').getByRole('button').click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('历史主动作')
  await expect(dialog).not.toContainText('当前综合解释')
  expect(productRequests(fixture, 'explanation')).toHaveLength(0)
  await page.mouse.click(4, 4)
  await expect(dialog).not.toBeVisible()
  assertNoUnexpectedRequests(fixture)
})

for (const [mode, close, color] of [['up', 105, 'rgb(255, 64, 58)'], ['down', 95, 'rgb(34, 185, 93)'], ['neutral', 100, 'rgb(32, 36, 43)'], ['unavailable', null, 'rgb(32, 36, 43)']]) {
  test(`Newow headline quote uses ${mode} direction color`, async ({ page }) => {
    await installNewowProductFixtures(page)
    await page.route('**/api/v1/market/bars/page?**', async route => {
      if (close === null) return route.abort('failed')
      const bars = [100, close].map((value, index) => ({ bar_end: `2026-09-0${index + 2}T07:00:00Z`, trading_day: `2026-09-0${index + 2}`, open: 100, high: 110, low: 90, close: value, volume: 1, turnover: null, open_interest: null }))
      await route.fulfill({ json: { request: { series_kind: 'actual_dominant', symbol: 'rb', contract: null, frequency: '1d', before: null, limit: 2 }, bars, canonical_coverage: { start: bars[0].bar_end, end: bars[1].bar_end }, page: { has_more_before: false, next_before: null }, resolved_contract_segments: [{ contract: 'RB2605', start_trading_day: '2026-01-01', end_trading_day: '2026-12-31' }] } })
    })
    await page.goto(newowRoute())
    const headline = page.locator('.quote-header__price strong')
    await expect(headline).toHaveText(close === null ? '—' : `${close.toFixed(2)}`)
    await expect(headline).toHaveCSS('color', color)
  })
}


test('historical exact locate keeps window state separate from current explanation in inline and modal views', async ({ page }) => {
  const fixture = await installNewowProductFixtures(page)
  await page.route('**/api/v1/market/newow/strategy-detail?**', async route => {
    if (new URL(route.request().url()).searchParams.get('section') !== 'explanation') return route.fallback()
    const payload = buildNewowFixtureEnvelopeForTest('explanation')
    payload.explanation.value.context.daily.main_state = 'HOLD'
    return route.fulfill({ json: payload })
  })
  await page.goto(newowRoute())
  await expect(page.locator('[data-detail-workspace="newow"]')).toHaveAttribute('data-chart-state', 'ready')
  await page.locator('.newow-reference').scrollIntoViewIfNeeded()
  await page.getByRole('button', { name: '加载更多参考历史', exact: true }).click()
  await page.getByRole('button', { name: /定位参考记录 trend-1d-interrupted/ }).click()
  await expect(page.getByTestId('newow-product-chart-stage')).toHaveAttribute('data-selected-signal-id', 'trend-1d-bi')
  expect(productRequests(fixture, 'chart').at(-1).url.searchParams.get('from')).toBe('2026-01-05')
  await page.getByRole('button', { name: '展开详情', exact: true }).click()
  const inline = page.locator('#newow-details')
  await expect(inline.getByTestId('newow-window-state')).toContainText('所示历史 Bar 的策略状态为建仓')
  await expect(inline.getByTestId('newow-window-state')).not.toContainText('当前')
  await expect(inline.getByTestId('newow-explanation-panel')).toContainText('当前快照截至 09-03 16:00')
  await expect(inline.getByTestId('newow-explanation-panel')).not.toContainText('策略当前为建仓')
  await page.getByRole('button', { name: '策略信息', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByTestId('newow-window-state')).toContainText('所示历史窗口状态')
  await expect(dialog.getByTestId('newow-window-state')).toContainText('01-05 15:00')
  await expect(dialog.getByTestId('newow-window-state')).not.toContainText('当前')
  const current = dialog.getByTestId('newow-explanation-panel')
  await expect(current).toContainText('当前快照截至 09-03 16:00')
  await current.getByText('来源与证据详情', { exact: true }).click()
  await current.getByText('多周期来源上下文', { exact: true }).first().click()
  await expect(current.locator('tr').filter({ hasText: '1d' }).first()).toContainText('HOLD')
  await expect(current).toContainText('2026-09-03T08:00:00.000Z')
  await page.screenshot({ path: '/private/tmp/newow-task2-history-dialog.png' })
  assertNoUnexpectedRequests(fixture)
})

for (const [width, height] of [[1280, 800], [1440, 900], [1920, 1080], [2560, 1440], [390, 844]]) {
  test(`white detail ${width}x${height}: controlled rich rendering, vertical cards and disclosure`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    const fixture = await installNewowProductFixtures(page, { visualRich: true })
    await page.goto(newowRoute())
    const stage = page.getByTestId('newow-product-chart-stage')
    await expect(stage).toHaveAttribute('data-auxiliary-state', 'ready')
    expect(productRequests(fixture, 'explanation')).toHaveLength(0)
    expect(productRequests(fixture, 'comparator')).toHaveLength(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.locator('.newow-reference').scrollIntoViewIfNeeded()
    await expect(page.getByTestId('newow-reference-summary')).toBeVisible()
    const summary = await page.getByTestId('newow-reference-summary').innerText()
    await page.getByRole('button', { name: '加载更多参考历史' }).click()
    await expect(page.locator('article[data-reference-category]')).toHaveCount(4)
    await expect(page.locator('article[data-reference-category="open"] .newow-return-badge')).toHaveAttribute('data-direction', 'down')
    await expect(page.locator('article[data-reference-category="closed"] .newow-return-badge').first()).toHaveAttribute('data-direction', 'up')
    await expect(page.locator('article[data-reference-category="open"]')).not.toContainText('T07:00:00.000Z')
    await expect(page.locator('article[data-reference-category="interrupted"]')).toContainText('物理合约区段结束')
    await expect(page.locator('article[data-reference-category="interrupted"]')).not.toContainText('OWNER_BOUNDARY')
    await page.getByRole('combobox', { name: '筛选参考历史' }).selectOption('open')
    await expect(page.locator('article[data-reference-category]')).toHaveCount(1)
    expect(await page.getByTestId('newow-reference-summary').innerText()).toBe(summary)
    await page.getByRole('combobox', { name: '筛选参考历史' }).selectOption('all')
    await page.getByTestId('newow-product-chart-stage').scrollIntoViewIfNeeded()
    await page.locator('.newow-reference').scrollIntoViewIfNeeded()
    expect(productRequests(fixture, 'reference')).toHaveLength(2)
    expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeGreaterThan(height)
    await page.evaluate(() => window.scrollTo(0, 0))
    await expect(page.locator('.newow-brand')).toBeInViewport()
    await page.mouse.move(0, 0)
    await expect(page).toHaveScreenshot(`newow-light-${width}.png`, { fullPage: true, animations: 'disabled', maxDiffPixels: 500 })
    const collapsedY = (await stage.boundingBox()).y
    const expand = page.getByRole('button', { name: '展开详情', exact: true })
    await expand.click()
    await expect(page.locator('#newow-details')).toBeVisible()
    await expect(page.locator('#newow-details')).toContainText('部分解释证据不足')
    expect((await stage.boundingBox()).y).toBeGreaterThan(collapsedY)
    await expect(expand).toHaveCount(0)
    await page.getByRole('button', { name: '收起详情', exact: true }).click()
    const trigger = page.getByRole('button', { name: '策略信息', exact: true })
    await trigger.click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    await expect(dialog.getByRole('button', { name: '关闭解释', exact: true })).toBeFocused()
    expect(await dialog.locator('.newow-detail-dialog__body').evaluate(element => element.scrollTop)).toBe(0)
    if (width === 1440 || width === 390) await expect(page).toHaveScreenshot(`newow-light-dialog-${width}.png`, { animations: 'disabled', maxDiffPixels: 500 })
    for (let index = 0; index < 12; index++) {
      await page.keyboard.press('Tab')
      expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
    }
    await page.keyboard.press('Shift+Tab')
    expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(dialog).not.toBeVisible()
    await expect(trigger).toBeFocused()
    await trigger.click()
    await page.mouse.click(4, 4)
    await expect(dialog).not.toBeVisible()
    await expect(trigger).toBeFocused()
    if (width === 390) expect((await trigger.boundingBox()).height).toBeGreaterThanOrEqual(44)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    assertNoUnexpectedRequests(fixture)
    await testInfo.attach('provenance', { body: 'Local intercepted, coherent synthetic fixture. Approved generated art is a layout/color reference; neither image proves market facts or source page parity.', contentType: 'text/plain' })
  })
}

test('old backend MACD rejection and reference failure stay explicit and retry only on request', async ({ page }) => {
  const fixture = await installNewowProductFixtures(page, { onProductRequest: async ({ route, url, count }) => {
    if (url.searchParams.get('component') === 'macd') { await route.fulfill({ status: 422, json: { detail: { code: 'NEWOW_MACD_UNSUPPORTED' } } }); return 'handled' }
    if (url.searchParams.get('section') === 'reference' && count === 1) { await route.fulfill({ status: 503, json: { detail: { code: 'NEWOW_API_UNAVAILABLE' } } }); return 'handled' }
  } })
  await page.goto(newowRoute())
  await expect(page.getByTestId('newow-product-chart-stage')).toHaveAttribute('data-auxiliary-state', 'error')
  await expect(page.locator('[role="status"]').filter({ hasText: '辅助图层不可用' }).first()).toBeVisible()
  await page.locator('.newow-reference').scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: '重试参考交易' })).toBeVisible()
  await page.getByTestId('newow-product-chart-stage').scrollIntoViewIfNeeded()
  await page.locator('.newow-reference').scrollIntoViewIfNeeded()
  expect(productRequests(fixture, 'reference')).toHaveLength(1)
  expect(productRequests(fixture, 'auxiliary')).toHaveLength(1)
  await page.getByRole('button', { name: '重试参考交易' }).click()
  await expect(page.getByTestId('newow-reference-summary')).toBeVisible()
  expect(productRequests(fixture, 'reference')).toHaveLength(2)
  assertNoUnexpectedRequests(fixture)
})


for (const width of [1440, 390]) {
  test(`current FLAT waiting card is independent from paged returns at ${width}`, async ({ page }, testInfo) => {
    const fixture = await installNewowProductFixtures(page, {
      onProductRequest: async ({ route, section, strategy, frequency }) => {
        if (!['chart', 'reference'].includes(section)) return
        const payload = buildNewowFixtureEnvelopeForTest(section, strategy, frequency, false, null, { noAction: true, zeroClosed: true })
        if (section === 'chart') {
          const bar = { ...payload.chart.value.bars.at(-1), bar_end: '2026-09-03T07:00:00.000Z', trading_day: '2026-09-03' }
          payload.chart.value.bars.push(bar)
          payload.chart.value.frames.forEach(frame => { frame.main_state = 'FLAT' })
          payload.chart.value.frames.push({ ...payload.chart.value.frames.at(-1), bar_end: bar.bar_end, main_state: 'FLAT' })
        } else {
          payload.reference.value.items = []
          payload.reference.value.summary.open_count = 0
          payload.reference.value.summary.interrupted_count = 0
          payload.reference.value.summary.initial_count = 0
        }
        await route.fulfill({ json: payload })
        return 'handled'
      },
    })
    await page.setViewportSize({ width, height: 900 })
    await page.goto(newowRoute())
    await expect(page.locator('[data-detail-workspace="newow"]')).toHaveAttribute('data-chart-state', 'ready')
    await page.locator('.newow-reference').scrollIntoViewIfNeeded()
    const waiting = page.getByTestId('newow-reference-waiting')
    await expect(waiting).toContainText('空仓等待中')
    await expect(waiting).toContainText('状态时间 2026-09-03')
    await expect(waiting).not.toContainText('%')
    await expect(waiting).toHaveCSS('border-left-color', 'rgb(57, 123, 209)')
    await page.getByLabel('筛选参考历史').selectOption('interrupted')
    await expect(waiting).toBeVisible()
    await expect(page.getByTestId('newow-reference-summary')).toContainText('暂无已完成参考交易')
    await page.locator('.newow-reference').screenshot({ path: testInfo.outputPath(`waiting-reference-${width}.png`) })
    assertNoUnexpectedRequests(fixture)
  })
}
